// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA40g3yOJmjsB_jBaWoTh-P0yYgOA2Mz00',
    appId: '1:331552180653:web:6fe0c00b5530f4dfb87924',
    messagingSenderId: '331552180653',
    projectId: 'edu-vista000',
    authDomain: 'edu-vista000.firebaseapp.com',
    storageBucket: 'edu-vista000.appspot.com',
    measurementId: 'G-545E3CDXQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCTF0XxXlxyuMIwvHonz9ZWu31HMxkvbI',
    appId: '1:331552180653:android:cc7dfe1bbe3ab1ccb87924',
    messagingSenderId: '331552180653',
    projectId: 'edu-vista000',
    storageBucket: 'edu-vista000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwYJ-eaVhTQNuEMjcCRJvds1dodAOQFNo',
    appId: '1:331552180653:ios:883a0c53bea69913b87924',
    messagingSenderId: '331552180653',
    projectId: 'edu-vista000',
    storageBucket: 'edu-vista000.appspot.com',
    iosBundleId: 'com.example.eduVista',
  );
}
